-- Phase 2 direct PostgreSQL schema and demo data.
--
-- Run after Laravel's base migrations have created the users table:
--
--   psql -U postgres -d tourismeldieb -f database/sql/phase2_postgresql_schema_seed.sql
--
-- This script mirrors the Phase 2 Laravel migrations and seeders added to the
-- project. It is intentionally PostgreSQL-specific and uses ON CONFLICT for
-- repeatable demo data loading.

BEGIN;

CREATE TABLE IF NOT EXISTS languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    native_name VARCHAR(255) NOT NULL,
    direction VARCHAR(3) NOT NULL DEFAULT 'ltr',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code CHAR(3) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    symbol VARCHAR(12) NOT NULL,
    decimal_places SMALLINT NOT NULL DEFAULT 2,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_id BIGINT NULL REFERENCES currencies(id) ON DELETE SET NULL,
    code CHAR(2) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    phone_code VARCHAR(12) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS destinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT NULL REFERENCES countries(id) ON DELETE SET NULL,
    code VARCHAR(255) NOT NULL UNIQUE,
    timezone VARCHAR(255) NOT NULL DEFAULT 'Africa/Cairo',
    image_url VARCHAR(1000) NULL,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS destination_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
    locale VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    short_description TEXT NULL,
    description TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE (destination_id, locale),
    UNIQUE (locale, slug)
);

CREATE TABLE IF NOT EXISTS tour_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NULL REFERENCES tour_categories(id) ON DELETE SET NULL,
    code VARCHAR(255) NOT NULL UNIQUE,
    image_url VARCHAR(1000) NULL,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS tour_category_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_category_id BIGINT NOT NULL REFERENCES tour_categories(id) ON DELETE CASCADE,
    locale VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE (tour_category_id, locale),
    UNIQUE (locale, slug)
);

CREATE TABLE IF NOT EXISTS tours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT NOT NULL REFERENCES destinations(id) ON DELETE RESTRICT,
    tour_category_id BIGINT NULL REFERENCES tour_categories(id) ON DELETE SET NULL,
    code VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    duration_value SMALLINT NULL,
    duration_unit VARCHAR(20) NULL,
    tour_type VARCHAR(20) NOT NULL DEFAULT 'shared',
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_best_seller BOOLEAN NOT NULL DEFAULT FALSE,
    is_last_minute BOOLEAN NOT NULL DEFAULT FALSE,
    minimum_age SMALLINT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    published_at TIMESTAMP NULL,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS tour_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
    locale VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    short_description TEXT NULL,
    description TEXT NULL,
    highlights JSONB NULL,
    itinerary JSONB NULL,
    included JSONB NULL,
    excluded JSONB NULL,
    faqs JSONB NULL,
    seo_title VARCHAR(255) NULL,
    seo_description TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE (tour_id, locale),
    UNIQUE (locale, slug)
);

CREATE TABLE IF NOT EXISTS tour_operating_languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
    language_id BIGINT NOT NULL REFERENCES languages(id) ON DELETE RESTRICT,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE (tour_id, language_id)
);

CREATE TABLE IF NOT EXISTS tour_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT NOT NULL REFERENCES tours(id) ON DELETE RESTRICT,
    code VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    minimum_guests SMALLINT NOT NULL DEFAULT 1 CHECK (minimum_guests >= 1),
    maximum_guests SMALLINT NOT NULL,
    minimum_booking_quantity SMALLINT NOT NULL DEFAULT 1 CHECK (minimum_booking_quantity >= 1),
    maximum_booking_quantity SMALLINT NOT NULL,
    duration_value SMALLINT NULL,
    duration_unit VARCHAR(20) NOT NULL DEFAULT 'hour',
    is_private BOOLEAN NOT NULL DEFAULT FALSE,
    requires_manual_confirmation BOOLEAN NOT NULL DEFAULT FALSE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order SMALLINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    UNIQUE (tour_id, code),
    CHECK (maximum_guests >= minimum_guests),
    CHECK (maximum_booking_quantity <= capacity)
);

CREATE TABLE IF NOT EXISTS tour_option_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
    tour_option_id BIGINT NOT NULL REFERENCES tour_options(id) ON DELETE CASCADE,
    locale VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    short_description TEXT NULL,
    description TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE (tour_option_id, locale),
    UNIQUE (tour_id, locale, slug)
);

CREATE TABLE IF NOT EXISTS tour_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_option_id BIGINT NOT NULL REFERENCES tour_options(id) ON DELETE RESTRICT,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NULL,
    capacity_override INTEGER NULL CHECK (capacity_override IS NULL OR capacity_override > 0),
    pickup_start_time TIME NULL,
    booking_cutoff_hours SMALLINT NOT NULL DEFAULT 24 CHECK (booking_cutoff_hours >= 0),
    booking_opens_days_before SMALLINT NOT NULL DEFAULT 90,
    valid_from DATE NULL,
    valid_to DATE NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE TABLE IF NOT EXISTS tour_departures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_option_id BIGINT NOT NULL REFERENCES tour_options(id) ON DELETE RESTRICT,
    tour_schedule_id BIGINT NULL REFERENCES tour_schedules(id) ON DELETE SET NULL,
    departure_date DATE NOT NULL,
    start_datetime TIMESTAMP NOT NULL,
    end_datetime TIMESTAMP NULL,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    reserved_capacity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_capacity >= 0),
    confirmed_capacity INTEGER NOT NULL DEFAULT 0 CHECK (confirmed_capacity >= 0),
    available_capacity INTEGER NOT NULL DEFAULT 0 CHECK (available_capacity >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    booking_opens_at TIMESTAMP NULL,
    booking_cutoff_at TIMESTAMP NULL,
    manual_notes TEXT NULL,
    generated_automatically BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    UNIQUE (tour_option_id, start_datetime),
    CHECK (reserved_capacity + confirmed_capacity <= capacity)
);

CREATE TABLE IF NOT EXISTS tour_blackout_dates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT NOT NULL REFERENCES tours(id) ON DELETE RESTRICT,
    tour_option_id BIGINT NULL REFERENCES tour_options(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(255) NULL,
    internal_notes TEXT NULL,
    cancel_existing_departures BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS tour_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_option_id BIGINT NOT NULL REFERENCES tour_options(id) ON DELETE RESTRICT,
    guest_type VARCHAR(30) NOT NULL,
    currency_id BIGINT NOT NULL REFERENCES currencies(id) ON DELETE RESTRICT,
    amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
    minimum_quantity SMALLINT NOT NULL DEFAULT 1,
    maximum_quantity SMALLINT NULL,
    valid_from DATE NULL,
    valid_to DATE NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE TABLE IF NOT EXISTS pricing_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT NOT NULL REFERENCES tours(id) ON DELETE RESTRICT,
    tour_option_id BIGINT NULL REFERENCES tour_options(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    rule_type VARCHAR(30) NOT NULL,
    adjustment_type VARCHAR(40) NOT NULL,
    adjustment_value INTEGER NOT NULL,
    currency_id BIGINT NULL REFERENCES currencies(id) ON DELETE RESTRICT,
    priority INTEGER NOT NULL DEFAULT 0,
    starts_at TIMESTAMP NULL,
    ends_at TIMESTAMP NULL,
    days_of_week JSONB NULL,
    minimum_guests SMALLINT NULL,
    maximum_guests SMALLINT NULL,
    minimum_days_before SMALLINT NULL,
    maximum_days_before SMALLINT NULL,
    applies_to_guest_type VARCHAR(30) NULL,
    stacking_mode VARCHAR(30) NOT NULL DEFAULT 'stackable',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at),
    CHECK (maximum_guests IS NULL OR minimum_guests IS NULL OR maximum_guests >= minimum_guests),
    CHECK (maximum_days_before IS NULL OR minimum_days_before IS NULL OR maximum_days_before >= minimum_days_before)
);

CREATE TABLE IF NOT EXISTS currency_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency_id BIGINT NOT NULL REFERENCES currencies(id) ON DELETE RESTRICT,
    target_currency_id BIGINT NOT NULL REFERENCES currencies(id) ON DELETE RESTRICT,
    rate NUMERIC(20, 10) NOT NULL,
    effective_at TIMESTAMP NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    UNIQUE (base_currency_id, target_currency_id, effective_at)
);

CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    discount_type VARCHAR(30) NOT NULL,
    discount_value INTEGER NOT NULL,
    currency_id BIGINT NULL REFERENCES currencies(id) ON DELETE RESTRICT,
    maximum_discount_minor BIGINT NULL,
    minimum_order_minor BIGINT NULL,
    usage_limit INTEGER NULL,
    usage_limit_per_customer INTEGER NULL,
    used_count INTEGER NOT NULL DEFAULT 0,
    starts_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    CHECK (expires_at IS NULL OR starts_at IS NULL OR expires_at >= starts_at)
);

CREATE TABLE IF NOT EXISTS coupon_tour (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id BIGINT NOT NULL REFERENCES coupons(id) ON DELETE CASCADE,
    tour_id BIGINT NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE (coupon_id, tour_id)
);

CREATE TABLE IF NOT EXISTS coupon_tour_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id BIGINT NOT NULL REFERENCES coupons(id) ON DELETE CASCADE,
    tour_option_id BIGINT NOT NULL REFERENCES tour_options(id) ON DELETE CASCADE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE (coupon_id, tour_option_id)
);

CREATE INDEX IF NOT EXISTS languages_active_index ON languages (is_active);
CREATE INDEX IF NOT EXISTS currencies_default_index ON currencies (is_default);
CREATE INDEX IF NOT EXISTS currencies_active_index ON currencies (is_active);
CREATE INDEX IF NOT EXISTS destinations_active_index ON destinations (is_active);
CREATE INDEX IF NOT EXISTS tours_destination_status_index ON tours (destination_id, status);
CREATE INDEX IF NOT EXISTS tours_category_status_index ON tours (tour_category_id, status);
CREATE INDEX IF NOT EXISTS tour_options_tour_active_index ON tour_options (tour_id, is_active);
CREATE INDEX IF NOT EXISTS tour_options_tour_default_index ON tour_options (tour_id, is_default);
CREATE UNIQUE INDEX IF NOT EXISTS tour_options_one_default_per_tour ON tour_options (tour_id) WHERE is_default = TRUE AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS tour_option_translations_locale_slug_index ON tour_option_translations (locale, slug);
CREATE INDEX IF NOT EXISTS tour_schedules_option_day_active_index ON tour_schedules (tour_option_id, day_of_week, is_active);
CREATE INDEX IF NOT EXISTS tour_schedules_valid_range_index ON tour_schedules (valid_from, valid_to);
CREATE UNIQUE INDEX IF NOT EXISTS tour_schedules_active_unique_index ON tour_schedules (tour_option_id, day_of_week, start_time) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS tour_departures_status_date_index ON tour_departures (status, departure_date);
CREATE INDEX IF NOT EXISTS tour_departures_date_status_index ON tour_departures (departure_date, status);
CREATE INDEX IF NOT EXISTS tour_departures_cutoff_index ON tour_departures (booking_cutoff_at);
CREATE INDEX IF NOT EXISTS tour_blackout_dates_tour_range_index ON tour_blackout_dates (tour_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS tour_blackout_dates_option_range_index ON tour_blackout_dates (tour_option_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS tour_prices_option_guest_currency_index ON tour_prices (tour_option_id, guest_type, currency_id);
CREATE INDEX IF NOT EXISTS tour_prices_valid_active_index ON tour_prices (valid_from, valid_to, is_active);
CREATE UNIQUE INDEX IF NOT EXISTS tour_prices_active_unique_index ON tour_prices (tour_option_id, guest_type, currency_id, (COALESCE(valid_from, DATE '0001-01-01'))) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS pricing_rules_tour_active_index ON pricing_rules (tour_id, is_active);
CREATE INDEX IF NOT EXISTS pricing_rules_option_active_index ON pricing_rules (tour_option_id, is_active);
CREATE INDEX IF NOT EXISTS pricing_rules_period_index ON pricing_rules (starts_at, ends_at);
CREATE INDEX IF NOT EXISTS currency_rates_pair_active_index ON currency_rates (base_currency_id, target_currency_id, is_active);
CREATE INDEX IF NOT EXISTS coupons_active_period_index ON coupons (is_active, starts_at, expires_at);

INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at)
VALUES (
    'Demo Admin',
    'admin@hurgadaguide.example',
    NOW(),
    '$2y$12$7EqJtq98hPqEX7fNZaFWoOhi6emhBIDyK49eZKf1hbe10YvHldcKS',
    NOW(),
    NOW()
)
ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name, updated_at = NOW();

INSERT INTO permissions (name, guard_name, created_at, updated_at)
VALUES
    ('languages.view', 'web', NOW(), NOW()),
    ('currencies.view', 'web', NOW(), NOW()),
    ('countries.view', 'web', NOW(), NOW()),
    ('destinations.view', 'web', NOW(), NOW()),
    ('categories.view', 'web', NOW(), NOW()),
    ('tours.view', 'web', NOW(), NOW()),
    ('users.view', 'web', NOW(), NOW()),
    ('roles.view', 'web', NOW(), NOW()),
    ('settings.view', 'web', NOW(), NOW())
ON CONFLICT (name, guard_name) DO UPDATE SET updated_at = NOW();

INSERT INTO model_has_permissions (permission_id, model_type, model_id)
SELECT p.id, 'App\Models\User', u.id
FROM permissions p
JOIN users u ON u.email = 'admin@hurgadaguide.example'
WHERE p.name IN (
    'languages.view',
    'currencies.view',
    'countries.view',
    'destinations.view',
    'categories.view',
    'tours.view',
    'users.view',
    'roles.view',
    'settings.view'
)
ON CONFLICT DO NOTHING;

INSERT INTO languages (code, name, native_name, direction, is_active, sort_order, created_at, updated_at)
VALUES
    ('en', 'English', 'English', 'ltr', TRUE, 1, NOW(), NOW()),
    ('ar', 'Arabic', 'العربية', 'rtl', TRUE, 2, NOW(), NOW()),
    ('de', 'German', 'Deutsch', 'ltr', TRUE, 3, NOW(), NOW()),
    ('ru', 'Russian', 'Русский', 'ltr', TRUE, 4, NOW(), NOW())
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    native_name = EXCLUDED.native_name,
    direction = EXCLUDED.direction,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();

INSERT INTO currencies (code, name, symbol, decimal_places, is_default, is_active, sort_order, created_at, updated_at)
VALUES
    ('USD', 'US Dollar', '$', 2, TRUE, TRUE, 1, NOW(), NOW()),
    ('EUR', 'Euro', '€', 2, FALSE, TRUE, 2, NOW(), NOW()),
    ('EGP', 'Egyptian Pound', 'E£', 2, FALSE, TRUE, 3, NOW(), NOW())
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    symbol = EXCLUDED.symbol,
    decimal_places = EXCLUDED.decimal_places,
    is_default = EXCLUDED.is_default,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();

INSERT INTO countries (currency_id, code, name, phone_code, is_active, created_at, updated_at)
SELECT c.id, 'EG', 'Egypt', '+20', TRUE, NOW(), NOW()
FROM currencies c
WHERE c.code = 'USD'
ON CONFLICT (code) DO UPDATE
SET currency_id = EXCLUDED.currency_id,
    name = EXCLUDED.name,
    phone_code = EXCLUDED.phone_code,
    is_active = TRUE,
    updated_at = NOW();

INSERT INTO destinations (country_id, code, timezone, image_url, is_featured, is_active, sort_order, created_by, updated_by, created_at, updated_at)
SELECT countries.id, data.code, 'Africa/Cairo', data.image_url, data.is_featured, TRUE, data.sort_order, users.id, users.id, NOW(), NOW()
FROM (
    VALUES
        ('hurghada', 'https://images.unsplash.com/photo-1582972236019-ea4af5ffe587?auto=format&fit=crop&w=1200&q=80', TRUE, 1),
        ('el-gouna', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80', TRUE, 2),
        ('luxor', 'https://images.unsplash.com/photo-1604480133435-25b86862d276?auto=format&fit=crop&w=1200&q=80', FALSE, 3)
) AS data(code, image_url, is_featured, sort_order)
CROSS JOIN countries
CROSS JOIN users
WHERE countries.code = 'EG' AND users.email = 'admin@hurgadaguide.example'
ON CONFLICT (code) DO UPDATE
SET image_url = EXCLUDED.image_url,
    is_featured = EXCLUDED.is_featured,
    is_active = TRUE,
    sort_order = EXCLUDED.sort_order,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

INSERT INTO destination_translations (destination_id, locale, name, slug, short_description, description, created_at, updated_at)
SELECT d.id, data.locale, data.name, data.slug, data.short_description, data.short_description, NOW(), NOW()
FROM (
    VALUES
        ('hurghada', 'en', 'Hurghada', 'hurghada', 'A Red Sea base for islands, reefs, desert safaris, and family activities.'),
        ('hurghada', 'ar', 'الغردقة', 'hurghada', 'وجهة على البحر الأحمر للرحلات البحرية والسفاري والأنشطة العائلية.'),
        ('el-gouna', 'en', 'El Gouna', 'el-gouna', 'A lagoon town with boutique cruises, calm beaches, and relaxed evening trips.'),
        ('el-gouna', 'ar', 'الجونة', 'el-gouna', 'مدينة لاجونات هادئة لرحلات بحرية وتجارب مريحة.'),
        ('luxor', 'en', 'Luxor', 'luxor', 'Ancient temples, Nile views, and full-day cultural tours from the Red Sea.'),
        ('luxor', 'ar', 'الأقصر', 'luxor', 'معابد قديمة وإطلالات على النيل ورحلات ثقافية من البحر الأحمر.')
) AS data(code, locale, name, slug, short_description)
JOIN destinations d ON d.code = data.code
ON CONFLICT (destination_id, locale) DO UPDATE
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    short_description = EXCLUDED.short_description,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO tour_categories (code, is_featured, is_active, sort_order, created_by, updated_by, created_at, updated_at)
SELECT data.code, TRUE, TRUE, data.sort_order, users.id, users.id, NOW(), NOW()
FROM (
    VALUES
        ('sea-trips', 1),
        ('desert-safari', 2),
        ('cultural-tours', 3)
) AS data(code, sort_order)
CROSS JOIN users
WHERE users.email = 'admin@hurgadaguide.example'
ON CONFLICT (code) DO UPDATE
SET is_featured = TRUE,
    is_active = TRUE,
    sort_order = EXCLUDED.sort_order,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

INSERT INTO tour_category_translations (tour_category_id, locale, name, slug, description, created_at, updated_at)
SELECT c.id, data.locale, data.name, data.slug, data.description, NOW(), NOW()
FROM (
    VALUES
        ('sea-trips', 'en', 'Sea trips', 'sea-trips', 'Island days, snorkeling stops, and Red Sea swimming.'),
        ('sea-trips', 'ar', 'رحلات بحرية', 'sea-trips', 'جزر وسباحة وسنوركلينج في البحر الأحمر.'),
        ('desert-safari', 'en', 'Desert safari', 'desert-safari', 'Quad bikes, Bedouin stops, and sunset desert scenes.'),
        ('desert-safari', 'ar', 'سفاري صحراوي', 'desert-safari', 'دراجات رباعية ومحطات بدوية ومشاهد الغروب.'),
        ('cultural-tours', 'en', 'Cultural tours', 'cultural-tours', 'Temples, museums, Nile views, and guided history days.'),
        ('cultural-tours', 'ar', 'رحلات ثقافية', 'cultural-tours', 'معابد ومتاحف وإطلالات على النيل مع مرشدين.')
) AS data(code, locale, name, slug, description)
JOIN tour_categories c ON c.code = data.code
ON CONFLICT (tour_category_id, locale) DO UPDATE
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO tours (destination_id, tour_category_id, code, status, duration_value, duration_unit, tour_type, is_featured, is_best_seller, is_last_minute, published_at, created_by, updated_by, created_at, updated_at)
SELECT d.id, c.id, data.code, 'published', data.duration_value, 'hour', data.tour_type, data.is_featured, data.is_best_seller, data.is_last_minute, NOW(), u.id, u.id, NOW(), NOW()
FROM (
    VALUES
        ('orange-bay', 'hurghada', 'sea-trips', 8, 'shared', TRUE, TRUE, FALSE),
        ('quad-bike-safari', 'hurghada', 'desert-safari', 5, 'shared', TRUE, FALSE, TRUE),
        ('luxor-full-day', 'luxor', 'cultural-tours', 12, 'shared', FALSE, TRUE, FALSE)
) AS data(code, destination_code, category_code, duration_value, tour_type, is_featured, is_best_seller, is_last_minute)
JOIN destinations d ON d.code = data.destination_code
JOIN tour_categories c ON c.code = data.category_code
JOIN users u ON u.email = 'admin@hurgadaguide.example'
ON CONFLICT (code) DO UPDATE
SET destination_id = EXCLUDED.destination_id,
    tour_category_id = EXCLUDED.tour_category_id,
    status = 'published',
    duration_value = EXCLUDED.duration_value,
    duration_unit = EXCLUDED.duration_unit,
    tour_type = EXCLUDED.tour_type,
    is_featured = EXCLUDED.is_featured,
    is_best_seller = EXCLUDED.is_best_seller,
    is_last_minute = EXCLUDED.is_last_minute,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

INSERT INTO tour_translations (tour_id, locale, name, slug, short_description, description, highlights, included, excluded, created_at, updated_at)
SELECT t.id, data.locale, data.name, data.slug, data.short_description, data.description,
       '["Local guide","Organized pickup","Clear itinerary"]'::jsonb,
       '["Transfers","Guide support"]'::jsonb,
       '["Personal expenses"]'::jsonb,
       NOW(), NOW()
FROM (
    VALUES
        ('orange-bay', 'en', 'Orange Bay Snorkeling', 'orange-bay-snorkeling', 'A full Red Sea island day with snorkeling stops.', 'Sail from Hurghada to Orange Bay with guided snorkeling, beach time, lunch, and comfortable transfers.'),
        ('orange-bay', 'ar', 'سنوركلينج أورانج باي', 'orange-bay-snorkeling', 'يوم كامل في الجزيرة مع توقفات سنوركلينج.', 'رحلة بحرية من الغردقة إلى أورانج باي مع سنوركلينج وغداء وانتقالات مريحة.'),
        ('quad-bike-safari', 'en', 'Desert Safari Quad Bike', 'desert-safari-quad-bike', 'Ride desert trails and enjoy sunset views.', 'A guided desert adventure with quad biking, panoramic stops, and relaxed Bedouin-style hospitality.'),
        ('quad-bike-safari', 'ar', 'سفاري دباب رباعي', 'desert-safari-quad-bike', 'قيادة في الصحراء ومشاهدة الغروب.', 'مغامرة صحراوية منظمة بدبابات رباعية وتوقفات بانورامية وضيافة بدوية.'),
        ('luxor-full-day', 'en', 'Luxor Full-Day Tour', 'luxor-full-day-tour', 'Temples, Nile views, and guided history in one long day.', 'Travel from the Red Sea to Luxor for Karnak, the West Bank, Nile views, and guided cultural highlights.'),
        ('luxor-full-day', 'ar', 'رحلة الأقصر يوم كامل', 'luxor-full-day-tour', 'معابد وإطلالات على النيل وتاريخ في يوم واحد.', 'رحلة من البحر الأحمر إلى الأقصر لزيارة الكرنك والبر الغربي ومعالم ثقافية مع مرشد.')
) AS data(code, locale, name, slug, short_description, description)
JOIN tours t ON t.code = data.code
ON CONFLICT (tour_id, locale) DO UPDATE
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    short_description = EXCLUDED.short_description,
    description = EXCLUDED.description,
    highlights = EXCLUDED.highlights,
    included = EXCLUDED.included,
    excluded = EXCLUDED.excluded,
    updated_at = NOW();

INSERT INTO tour_operating_languages (tour_id, language_id, created_at, updated_at)
SELECT t.id, l.id, NOW(), NOW()
FROM (
    VALUES
        ('orange-bay', 'en'), ('orange-bay', 'ar'), ('orange-bay', 'de'),
        ('quad-bike-safari', 'en'), ('quad-bike-safari', 'ar'), ('quad-bike-safari', 'ru'),
        ('luxor-full-day', 'en'), ('luxor-full-day', 'ar')
) AS data(tour_code, language_code)
JOIN tours t ON t.code = data.tour_code
JOIN languages l ON l.code = data.language_code
ON CONFLICT (tour_id, language_id) DO UPDATE SET updated_at = NOW();

INSERT INTO tour_options (tour_id, code, capacity, minimum_guests, maximum_guests, minimum_booking_quantity, maximum_booking_quantity, duration_value, duration_unit, is_private, requires_manual_confirmation, is_default, is_active, sort_order, created_by, updated_by, created_at, updated_at)
SELECT t.id, data.code, data.capacity, 1, data.maximum_guests, 1, data.maximum_booking_quantity, data.duration_value, 'hour',
       data.is_private, data.is_private, data.is_default, TRUE, data.sort_order, u.id, u.id, NOW(), NOW()
FROM (
    VALUES
        ('orange-bay', 'shared-boat-trip', 30, 30, 10, 8, FALSE, TRUE, 1),
        ('orange-bay', 'vip-boat-trip', 14, 14, 8, 8, FALSE, FALSE, 2),
        ('orange-bay', 'private-yacht', 10, 10, 1, 8, TRUE, FALSE, 3),
        ('quad-bike-safari', 'single-quad', 20, 20, 10, 5, FALSE, TRUE, 1),
        ('quad-bike-safari', 'double-quad', 20, 20, 10, 5, FALSE, FALSE, 2),
        ('quad-bike-safari', 'private-safari', 8, 8, 1, 5, TRUE, FALSE, 3),
        ('luxor-full-day', 'shared-bus', 42, 42, 8, 12, FALSE, TRUE, 1),
        ('luxor-full-day', 'small-group', 12, 12, 8, 12, FALSE, FALSE, 2),
        ('luxor-full-day', 'private-car', 4, 4, 1, 12, TRUE, FALSE, 3)
) AS data(tour_code, code, capacity, maximum_guests, maximum_booking_quantity, duration_value, is_private, is_default, sort_order)
JOIN tours t ON t.code = data.tour_code
JOIN users u ON u.email = 'admin@hurgadaguide.example'
ON CONFLICT (tour_id, code) DO UPDATE
SET capacity = EXCLUDED.capacity,
    maximum_guests = EXCLUDED.maximum_guests,
    maximum_booking_quantity = EXCLUDED.maximum_booking_quantity,
    duration_value = EXCLUDED.duration_value,
    is_private = EXCLUDED.is_private,
    requires_manual_confirmation = EXCLUDED.requires_manual_confirmation,
    is_default = EXCLUDED.is_default,
    is_active = TRUE,
    sort_order = EXCLUDED.sort_order,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

INSERT INTO tour_option_translations (tour_id, tour_option_id, locale, name, slug, short_description, description, created_at, updated_at)
SELECT o.tour_id, o.id, data.locale, data.name, data.slug, data.copy, data.copy || ' Availability, capacity, and prices are managed from the Phase 2 tables.', NOW(), NOW()
FROM (
    VALUES
        ('shared-boat-trip', 'en', 'Shared Boat Trip', 'shared-boat-trip', 'A reliable shared option with transfers, lunch, and guided snorkeling.'),
        ('shared-boat-trip', 'ar', 'رحلة قارب مشتركة', 'shared-boat-trip', 'خيار مشترك موثوق مع انتقالات وغداء وسنوركلينج.'),
        ('vip-boat-trip', 'en', 'VIP Boat Trip', 'vip-boat-trip', 'A smaller group boat day with more comfort and a relaxed pace.'),
        ('vip-boat-trip', 'ar', 'رحلة قارب فاخرة', 'vip-boat-trip', 'يوم بحري لمجموعة أصغر براحة أعلى وإيقاع هادئ.'),
        ('private-yacht', 'en', 'Private Yacht', 'private-yacht', 'A private group yacht experience with flexible timing.'),
        ('private-yacht', 'ar', 'يخت خاص', 'private-yacht', 'تجربة يخت خاصة للمجموعات مع توقيت مرن.'),
        ('single-quad', 'en', 'Single Quad', 'single-quad', 'One guest per quad for a classic desert ride.'),
        ('single-quad', 'ar', 'دباب فردي', 'single-quad', 'ضيف واحد لكل دباب لرحلة صحراوية كلاسيكية.'),
        ('double-quad', 'en', 'Double Quad', 'double-quad', 'Two guests sharing one quad with guided desert stops.'),
        ('double-quad', 'ar', 'دباب مزدوج', 'double-quad', 'ضيفان على دباب واحد مع توقفات صحراوية.'),
        ('private-safari', 'en', 'Private Safari', 'private-safari', 'A private desert route for families or small groups.'),
        ('private-safari', 'ar', 'سفاري خاص', 'private-safari', 'مسار صحراوي خاص للعائلات أو المجموعات الصغيرة.'),
        ('shared-bus', 'en', 'Shared Bus', 'shared-bus', 'A full-day cultural route by shared coach.'),
        ('shared-bus', 'ar', 'أتوبيس مشترك', 'shared-bus', 'رحلة ثقافية يوم كامل بأتوبيس مشترك.'),
        ('small-group', 'en', 'Small Group', 'small-group', 'A smaller Luxor day with more flexible pacing.'),
        ('small-group', 'ar', 'مجموعة صغيرة', 'small-group', 'رحلة أقصر لمجموعة أصغر بإيقاع أكثر مرونة.'),
        ('private-car', 'en', 'Private Car', 'private-car', 'A private vehicle and tailored timing for the Luxor route.'),
        ('private-car', 'ar', 'سيارة خاصة', 'private-car', 'سيارة خاصة وتوقيت مرن لمسار الأقصر.')
) AS data(option_code, locale, name, slug, copy)
JOIN tour_options o ON o.code = data.option_code
ON CONFLICT (tour_option_id, locale) DO UPDATE
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    short_description = EXCLUDED.short_description,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO tour_schedules (tour_option_id, day_of_week, start_time, end_time, pickup_start_time, booking_cutoff_hours, booking_opens_days_before, valid_from, valid_to, is_active, created_by, updated_by, created_at, updated_at)
SELECT o.id, data.day_of_week, data.start_time::time, (data.start_time::time + (o.duration_value || ' hours')::interval)::time,
       (data.start_time::time - interval '45 minutes')::time, 24, 90, DATE '2026-01-01', NULL, TRUE, u.id, u.id, NOW(), NOW()
FROM (
    VALUES
        ('orange-bay', 'sunday', '08:00'), ('orange-bay', 'tuesday', '08:00'), ('orange-bay', 'thursday', '08:00'),
        ('quad-bike-safari', 'monday', '15:00'), ('quad-bike-safari', 'wednesday', '15:00'), ('quad-bike-safari', 'friday', '15:00'),
        ('luxor-full-day', 'monday', '05:00'), ('luxor-full-day', 'thursday', '05:00')
) AS data(tour_code, day_of_week, start_time)
JOIN tours t ON t.code = data.tour_code
JOIN tour_options o ON o.tour_id = t.id
JOIN users u ON u.email = 'admin@hurgadaguide.example'
ON CONFLICT (tour_option_id, day_of_week, start_time) WHERE deleted_at IS NULL DO UPDATE
SET end_time = EXCLUDED.end_time,
    pickup_start_time = EXCLUDED.pickup_start_time,
    is_active = TRUE,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

INSERT INTO tour_departures (tour_option_id, tour_schedule_id, departure_date, start_datetime, end_datetime, capacity, reserved_capacity, confirmed_capacity, available_capacity, status, booking_opens_at, booking_cutoff_at, generated_automatically, created_by, updated_by, created_at, updated_at)
SELECT s.tour_option_id,
       s.id,
       (CURRENT_DATE + (7 + gs.week_offset * 7))::date,
       (((CURRENT_DATE + (7 + gs.week_offset * 7)) + s.start_time) AT TIME ZONE 'Africa/Cairo') AT TIME ZONE 'UTC',
       (((CURRENT_DATE + (7 + gs.week_offset * 7)) + s.end_time) AT TIME ZONE 'Africa/Cairo') AT TIME ZONE 'UTC',
       o.capacity,
       0,
       0,
       o.capacity,
       'available',
       ((((CURRENT_DATE + (7 + gs.week_offset * 7)) + s.start_time) AT TIME ZONE 'Africa/Cairo') AT TIME ZONE 'UTC') - interval '90 days',
       ((((CURRENT_DATE + (7 + gs.week_offset * 7)) + s.start_time) AT TIME ZONE 'Africa/Cairo') AT TIME ZONE 'UTC') - interval '24 hours',
       TRUE,
       u.id,
       u.id,
       NOW(),
       NOW()
FROM tour_schedules s
JOIN tour_options o ON o.id = s.tour_option_id
JOIN users u ON u.email = 'admin@hurgadaguide.example'
CROSS JOIN generate_series(0, 3) AS gs(week_offset)
WHERE s.is_active = TRUE
ON CONFLICT (tour_option_id, start_datetime) DO UPDATE
SET capacity = EXCLUDED.capacity,
    available_capacity = GREATEST(0, EXCLUDED.capacity - tour_departures.reserved_capacity - tour_departures.confirmed_capacity),
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

INSERT INTO tour_prices (tour_option_id, guest_type, currency_id, amount_minor, minimum_quantity, maximum_quantity, valid_from, valid_to, is_active, created_by, updated_by, created_at, updated_at)
SELECT o.id, data.guest_type, c.id, data.amount_minor, 1, NULL, DATE '2026-01-01', NULL, TRUE, u.id, u.id, NOW(), NOW()
FROM (
    VALUES
        ('shared-boat-trip', 'adult', 2500), ('shared-boat-trip', 'child', 1500), ('shared-boat-trip', 'infant', 0),
        ('vip-boat-trip', 'adult', 4500), ('vip-boat-trip', 'child', 2500), ('vip-boat-trip', 'infant', 0),
        ('private-yacht', 'private_group', 35000),
        ('single-quad', 'adult', 3500), ('single-quad', 'child', 2500),
        ('double-quad', 'adult', 3000), ('double-quad', 'child', 2000),
        ('private-safari', 'private_group', 22000),
        ('shared-bus', 'adult', 8500), ('shared-bus', 'child', 5500), ('shared-bus', 'infant', 0),
        ('small-group', 'adult', 12500), ('small-group', 'child', 8000), ('small-group', 'infant', 0),
        ('private-car', 'private_group', 42000)
) AS data(option_code, guest_type, amount_minor)
JOIN tour_options o ON o.code = data.option_code
JOIN currencies c ON c.code = 'USD'
JOIN users u ON u.email = 'admin@hurgadaguide.example'
ON CONFLICT (tour_option_id, guest_type, currency_id, (COALESCE(valid_from, DATE '0001-01-01'))) WHERE deleted_at IS NULL DO UPDATE
SET amount_minor = EXCLUDED.amount_minor,
    is_active = TRUE,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

INSERT INTO pricing_rules (tour_id, tour_option_id, name, rule_type, adjustment_type, adjustment_value, currency_id, priority, starts_at, ends_at, days_of_week, minimum_guests, minimum_days_before, stacking_mode, is_active, created_by, updated_by, created_at, updated_at)
SELECT t.id,
       o.id,
       data.name,
       data.rule_type,
       data.adjustment_type,
       data.adjustment_value,
       c.id,
       data.priority,
       date_trunc('year', NOW()),
       date_trunc('year', NOW()) + interval '1 year' - interval '1 second',
       data.days_of_week::jsonb,
       data.minimum_guests,
       data.minimum_days_before,
       data.stacking_mode,
       TRUE,
       u.id,
       u.id,
       NOW(),
       NOW()
FROM (
    VALUES
        ('orange-bay', NULL, 'Summer island demand', 'seasonal', 'percentage_increase', 1500, NULL, 10, '["friday","saturday"]', NULL, NULL, 'stackable'),
        ('orange-bay', 'shared-boat-trip', 'Early booking shared boat', 'early_booking', 'percentage_discount', 1000, NULL, 20, NULL, NULL, 7, 'stackable'),
        ('quad-bike-safari', NULL, 'Weekend safari increase', 'weekend', 'percentage_increase', 800, NULL, 15, '["friday","saturday"]', NULL, NULL, 'stackable'),
        ('quad-bike-safari', NULL, 'Group safari discount', 'group', 'percentage_discount', 1200, NULL, 30, NULL, 4, NULL, 'stackable'),
        ('luxor-full-day', NULL, 'Private car manual offer', 'manual_offer', 'fixed_discount', 5000, 'USD', 5, NULL, NULL, NULL, 'exclusive')
) AS data(tour_code, option_code, name, rule_type, adjustment_type, adjustment_value, currency_code, priority, days_of_week, minimum_guests, minimum_days_before, stacking_mode)
JOIN tours t ON t.code = data.tour_code
LEFT JOIN tour_options o ON o.code = data.option_code
LEFT JOIN currencies c ON c.code = data.currency_code
JOIN users u ON u.email = 'admin@hurgadaguide.example'
WHERE NOT EXISTS (
    SELECT 1 FROM pricing_rules existing WHERE existing.tour_id = t.id AND existing.name = data.name AND existing.deleted_at IS NULL
);

INSERT INTO currency_rates (base_currency_id, target_currency_id, rate, effective_at, is_active, created_by, updated_by, created_at, updated_at)
SELECT base_c.id, target_c.id, data.rate::numeric, CURRENT_DATE::timestamp, TRUE, u.id, u.id, NOW(), NOW()
FROM (
    VALUES
        ('USD', 'EUR', '0.9200000000'),
        ('USD', 'EGP', '48.5000000000'),
        ('EUR', 'USD', '1.0869565217'),
        ('EGP', 'USD', '0.0206185567')
) AS data(base_code, target_code, rate)
JOIN currencies base_c ON base_c.code = data.base_code
JOIN currencies target_c ON target_c.code = data.target_code
JOIN users u ON u.email = 'admin@hurgadaguide.example'
ON CONFLICT (base_currency_id, target_currency_id, effective_at) DO UPDATE
SET rate = EXCLUDED.rate,
    is_active = TRUE,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

INSERT INTO coupons (code, name, discount_type, discount_value, currency_id, maximum_discount_minor, minimum_order_minor, usage_limit, usage_limit_per_customer, used_count, starts_at, expires_at, is_active, created_by, updated_by, created_at, updated_at)
SELECT data.code, data.name, data.discount_type, data.discount_value, c.id, data.maximum_discount_minor, data.minimum_order_minor, 500, 1, 0,
       date_trunc('year', NOW()), date_trunc('year', NOW()) + interval '1 year' - interval '1 second', TRUE, u.id, u.id, NOW(), NOW()
FROM (
    VALUES
        ('SUNNY10', 'Sunny 10 percent', 'percentage', 1000, NULL, 5000, 5000),
        ('FAMILY25', 'Family fixed discount', 'fixed', 2500, 'USD', NULL, 10000)
) AS data(code, name, discount_type, discount_value, currency_code, maximum_discount_minor, minimum_order_minor)
LEFT JOIN currencies c ON c.code = data.currency_code
JOIN users u ON u.email = 'admin@hurgadaguide.example'
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    discount_type = EXCLUDED.discount_type,
    discount_value = EXCLUDED.discount_value,
    currency_id = EXCLUDED.currency_id,
    maximum_discount_minor = EXCLUDED.maximum_discount_minor,
    minimum_order_minor = EXCLUDED.minimum_order_minor,
    is_active = TRUE,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW();

INSERT INTO coupon_tour (coupon_id, tour_id, created_at, updated_at)
SELECT c.id, t.id, NOW(), NOW()
FROM (
    VALUES
        ('SUNNY10', 'orange-bay'), ('SUNNY10', 'quad-bike-safari'),
        ('FAMILY25', 'orange-bay'), ('FAMILY25', 'luxor-full-day')
) AS data(coupon_code, tour_code)
JOIN coupons c ON c.code = data.coupon_code
JOIN tours t ON t.code = data.tour_code
ON CONFLICT (coupon_id, tour_id) DO UPDATE SET updated_at = NOW();

INSERT INTO tour_blackout_dates (tour_id, tour_option_id, start_date, end_date, reason, internal_notes, cancel_existing_departures, is_active, created_by, updated_by, created_at, updated_at)
SELECT t.id, NULL, (CURRENT_DATE + interval '42 days')::date, (CURRENT_DATE + interval '42 days')::date,
       'Marine maintenance day', 'Demo blackout date for Phase 2 availability testing.', FALSE, TRUE, u.id, u.id, NOW(), NOW()
FROM tours t
JOIN users u ON u.email = 'admin@hurgadaguide.example'
WHERE t.code = 'orange-bay'
  AND NOT EXISTS (
      SELECT 1
      FROM tour_blackout_dates b
      WHERE b.tour_id = t.id
        AND b.start_date = (CURRENT_DATE + interval '42 days')::date
        AND b.deleted_at IS NULL
  );

COMMIT;
